- brew:
    - fish
    - fzf
    - git
    - go
    - jq
    - pyenv
    - pyenv-virtualenv
    - tmux
    - tree
    - vim
    - wget

- cask:
    - 1password
    - appcleaner
    - bartender
    - bettertouchtool
    - disk-inventory-x
    - docker
    - dozer
    - firefox
    - goland
    - google-chrome
    - google-cloud-sdk
    - iina
    - iterm2
    - keepingyouawake
    - postman
    - scroll-reverser
    - spotify
    - telegram
    - visual-studio-code
