repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        name: Scan for secrets
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.19.1
    hooks:
      - id: markdownlint-cli2
        name: Lint Markdown files
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.9.3
    hooks:
      - id: taplo-format
        name: Format TOML files
      - id: taplo-lint
        name: Lint TOML files
        args: ['--no-schema']
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        name: Format shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        name: Check shell script
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
        name: Format YAML files
        args: ["-formatter", "retain_line_breaks=true"]
