#!/usr/bin/env bash

set -e

usage() {
  cat <<USAGEEOF
Usage: $0 [profile]

The profile names can be found in meta/profiles.
USAGEEOF
    exit 0
}

[ -z $1 ] && { usage; }

BASE_CONFIG="install.conf.yaml"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIGS_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


cd "${BASE_DIR}"
git submodule update --init --recursive

# Read the contents of the profile config file and store it in a space
# separated string
while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "${META_DIR}/${PROFILES_DIR}/$1"

echo "contents of $1 file: $CONFIGS"
# Remove the input parameter from ${@}
shift

# Iterate through the configs in the profile and install them
for config in ${CONFIGS} ${@}; do
    echo -e "\nInstalling config $config"
    # Reset the cmd variable to an empty array
    cmd=()

    if [[ $config == *"debian"* ]]; then
        cmd=("${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" \
            -p "${BASE_DIR}/${META_DIR}/dotbot-apt/apt.py" \
            -c "${BASE_DIR}/${META_DIR}/${CONFIGS_DIR}/${config}${CONFIG_SUFFIX}"
        )
        cmd=(sudo "${cmd[@]}")
    elif [[ $config == *"darwin"* ]]; then
        cmd=("${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" \
            --plugin-dir dotbot-brew \
            -c "${BASE_DIR}/${META_DIR}/${CONFIGS_DIR}/${config}${CONFIG_SUFFIX}"
        )
    else
        cmd=("${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" \
            -c "${BASE_DIR}/${META_DIR}/${CONFIGS_DIR}/${config}${CONFIG_SUFFIX}"
        )
    fi

    echo "Running command ${cmd[@]}"
    "${cmd[@]}"
done
