#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
METADIR="meta"

cd "${BASEDIR}"
git submodule update --init --recursive

# Check if the script is running in GitHub Codespaces
if [ "$CODESPACES" = "true" ]; then
    # Install devcontainer packages
    ./install-devcontainer
# Check if the system is running Debian
elif [ -e /etc/debian_version ]; then
    # Install debian packages
    ./install-profile debian
# Check if the system is macOS
elif [ "$(uname -s)" == "Darwin" ]; then
    # Install macos packages
    ./install-profile darwin
else
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${BASEDIR}/${CONFIG}" "${@}"
fi
