version: "3"

includes:
  markdown:
    taskfile: git@github.com:michaelheyman/taskfiles.git//markdown/Taskfile.yml?ref=main
    aliases:
      - md
  pre-commit:
    taskfile: git@github.com:michaelheyman/taskfiles.git//pre-commit/Taskfile.yml?ref=main
    aliases:
      - pc

tasks:
  default:
    desc: default task
    cmds:
      - task --list

  install:
    desc: install dotfiles dependencies
    cmds:
      - task: pc:install
  
  docker:build:
    desc: build dotfiles docker image
    cmds:
      - docker build -t dotfiles -f .docker/Dockerfile .

  docker:clean:
    desc: clean up dotfiles docker image
    cmds:
      - docker rmi -f dotfiles

  docker:run:
    desc: run dotfiles docker image interactively
    cmds:
      - docker run -it --entrypoint sh dotfiles

  pre-commit:
    desc: run pre-commit checks
    cmds:
      - task: pc:run

  lint:
    desc: lint files
    cmds:
      - task: md:lint

  fmt:
    desc: format files
    cmds:
      - task: md:format
