#!/bin/bash

# This script requires you to have the ARTIFACTORY_USER and ARTIFACTORY_API_KEY environment variables set.
# See prerequisite:
# https://cambiahealth.atlassian.net/wiki/spaces/CCSE/pages/1532166397/100+-+Workstation+Set-Up#Section-2---Janus-Platform-Repository-Grab-Api-Key-and-set-up-.npmrc

if [[ -z "$ARTIFACTORY_USER" ]]; then
  echo "ARTIFACTORY_USER is not set. Please set it and re-run this script."
  exit 1
fi

if [[ -z "$ARTIFACTORY_API_KEY" ]]; then
  echo "ARTIFACTORY_API_KEY is not set. Please set it and re-run this script."
  exit 1
fi

NPM_AUTH=$(echo -n $ARTIFACTORY_USER:$ARTIFACTORY_API_KEY | base64)

# This overwrites any existing .npmrc file
echo registry=https://janusplatform.jfrog.io/janusplatform/api/npm/npm/ > .npmrc
echo _auth = "$NPM_AUTH" >> .npmrc
echo email = "$ARTIFACTORY_USER"@cambiahealth.com >> .npmrc
echo always-auth = true >> .npmrc

echo "Changing the mode of 'npmrc' to 755.." 
chmod 755 .npmrc

echo "npmrc file has been created in the current directory"
