#!/bin/bash

if [ $# -gt 1 ]
then
    echo "Usage: $0 <environment>"
    exit 1
fi

if [ $1 ]
then
    echo "docker-compose -f docker-compose-$1.yml up --build"
    docker-compose -f docker-compose-$1.yml up --build
else
    echo "docker-compose -f docker-compose.yml up --build"
    docker-compose -f docker-compose.yml up --build
fi
