#!/bin/bash

# Retrieves the JANUS_STACK_VERSION for all environments
# Requires jq, install it with brew install jq

jaio_environments=(dev uat prd)

if [ $# -ne 1 ]
then
    echo "Usage: $0 <stack-name>"
    exit 1
fi

stack_name=$1

function service_status() {
    stack=$1
    env=$2
    platform=janusplatform.io
    if [[ "$2" == *2 ]]
    then
        platform=healthsparq.com
    fi
    stack_version=$(curl -s -X GET "https://$stack.$env.$platform/env" | jq -r '.systemEnvironment.JANUS_STACK_VERSION')
    health_status=$(curl -s -X GET "https://$stack.$env.$platform/health" | jq -r '.status')
    if [[ -z $stack_version ]]
    then
        printf "%7s: %s %-5s %s\n" "$2" "$stack_version" "$health_status"
    else
        git_commit=$(curl -s -X GET "https://minerva-api.$env.$platform/api/deployments?service=$stack" | jq -r '.deployments[-1] | .["git-commit-url"]' | sed 's/.*commit\///')
        printf "%7s: %s %-5s %s\n" "$2" "$stack_version" "$health_status" "$git_commit"
    fi
}

echo "stack name: $stack_name"

for i in "${jaio_environments[@]}"
do 
    service_status "$stack_name" "$i"
done
