#!/bin/bash

# Runs Twistlock locally on an image. See docs for more details:
# https://cambiahealth.atlassian.net/wiki/spaces/INFOSEC/pages/3270421/Twistlock+CLI

if [ $# -ne 1 ]
then
    echo "Usage: $0 <image-name>"
    exit 1
fi

USER=r634237@regence.com
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker-registry.healthsparq.com/janus/security-container-scanner:latest $1 $USER
